"""Build platform-scroll-preview.html: platform-scroll.html with every font embedded as base64 so the preview works
offline: Aether Neue (Thin / Light / Medium, from fonts/) and DM Sans / DM Mono (Latin, from Google Fonts).
Usage (from the repo root): python3 scripts/build_platform_scroll_preview.py"""
import base64, re, subprocess

SRC, OUT = 'platform-scroll.html', 'platform-scroll-preview.html'
CSS_URL = 'https://fonts.googleapis.com/css2?family=DM+Mono:wght@400;500&family=DM+Sans:opsz,wght@9..40,400;9..40,500&display=swap'
UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/120 Safari/537.36'   # makes Google serve woff2


def fetch(url):
    return subprocess.run(['curl', '-sSf', '-A', UA, url], capture_output=True, check=True).stdout


css = fetch(CSS_URL).decode()
cache, faces = {}, []
for subset, block in re.findall(r'/\* ([\w-]+) \*/\s*(@font-face\s*\{[^}]*\})', css):
    if subset != 'latin':
        continue
    url = re.search(r'url\((https://[^)]+)\)', block).group(1)
    if url not in cache:
        cache[url] = 'data:font/woff2;base64,' + base64.b64encode(fetch(url)).decode()
    faces.append(block.replace(url, cache[url]))

html = open(SRC).read()
# Aether Neue: swap each local woff2 + woff pair for the embedded woff2
def embed_local(m):
    with open(m.group(1), 'rb') as f:
        return 'url("data:font/woff2;base64,' + base64.b64encode(f.read()).decode() + '") format("woff2")'
html = re.sub(r'url\("(fonts/[\w/]+\.woff2)"\) format\("woff2"\),url\("fonts/[\w/]+\.woff"\) format\("woff"\)', embed_local, html)
assert 'url("fonts/' not in html, 'preview still references fonts/ on disk'
html = re.sub(r'<link rel="preconnect"[^>]*>\n', '', html)
html = re.sub(r'<link href="https://fonts.googleapis.com[^>]*>\n', '', html)
html = html.replace('<title>Platform Scroll</title>', '<title>Platform Scroll Preview</title>')
html = html.replace('<style>\n', '<style>\n/* DM Sans + DM Mono (Latin) embedded below; Aether Neue embedded in its @font-face rules. Generated by scripts/build_platform_scroll_preview.py */\n'
                    + '\n'.join(faces) + '\n', 1)
assert 'https://' not in html, 'preview still references the network'
open(OUT, 'w').write(html)
print(OUT, len(faces), 'faces', round(len(html) / 1024), 'KB')
