"""Build platform-scroll-preview.html: platform-scroll.html with DM Sans / DM Mono (Latin) embedded as base64,
so the preview works offline. Aether Neue is not embedded; headings fall back to DM Sans.
Usage (from the repo root): python3 scripts/build_platform_scroll_preview.py"""
import base64, re, subprocess

SRC, OUT = 'platform-scroll.html', 'platform-scroll-preview.html'
CSS_URL = 'https://fonts.googleapis.com/css2?family=DM+Mono:wght@400;500&family=DM+Sans:opsz,wght@9..40,400;9..40,500&display=swap'
UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/120 Safari/537.36'   # makes Google serve woff2


def fetch(url):
    return subprocess.run(['curl', '-sSf', '-A', UA, url], capture_output=True, check=True).stdout


css = fetch(CSS_URL).decode()
cache, faces = {}, []
for subset, block in re.findall(r'/\* ([\w-]+) \*/\s*(@font-face\s*\{[^}]*\})', css):
    if subset != 'latin':
        continue
    url = re.search(r'url\((https://[^)]+)\)', block).group(1)
    if url not in cache:
        cache[url] = 'data:font/woff2;base64,' + base64.b64encode(fetch(url)).decode()
    faces.append(block.replace(url, cache[url]))

html = open(SRC).read()
html = re.sub(r'<link rel="preconnect"[^>]*>\n', '', html)
html = re.sub(r'<link href="https://fonts.googleapis.com[^>]*>\n', '', html)
html = html.replace('<title>Platform Scroll</title>', '<title>Platform Scroll Preview</title>')
html = html.replace('<style>\n', '<style>\n/* DM Sans + DM Mono (Latin), embedded so this preview works offline. Generated by scripts/build_platform_scroll_preview.py */\n'
                    + '\n'.join(faces) + '\n', 1)
assert 'https://' not in html, 'preview still references the network'
open(OUT, 'w').write(html)
print(OUT, len(faces), 'faces', round(len(html) / 1024), 'KB')
